//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDSHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIDSHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon BIDSHelper {
            get {
                object obj = ResourceManager.GetObject("BIDSHelper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Resource.
        /// </summary>
        internal static string BIDSHelperDescription {
            get {
                return ResourceManager.GetString("BIDSHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; 
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:as=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;
        ///	xmlns:dwd=&quot;http://schemas.microsoft.com/DataWarehouse/Designer/1.0&quot;&gt;
        ///	&lt;xsl:param name=&quot;TargetDatabase&quot;&gt;&lt;/xsl:param&gt;
        ///	&lt;xsl:param name=&quot;TargetCubeID&quot;&gt;&lt;/xsl:param&gt;
        ///
        ///	&lt;xsl:output indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;Batch xmlns=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;&gt;
        ///			&lt;xsl:apply-templates/&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployAggDesigns {
            get {
                return ResourceManager.GetString("DeployAggDesigns", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon DeployAggDesignsIcon {
            get {
                object obj = ResourceManager.GetObject("DeployAggDesignsIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; 
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:as=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;&gt;
        ///	&lt;xsl:param name=&quot;TargetDatabase&quot;&gt;&lt;/xsl:param&gt;
        ///
        ///	&lt;xsl:output indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;Alter AllowCreate=&quot;true&quot; ObjectExpansion=&quot;ExpandFull&quot; xmlns=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;&gt;
        ///			&lt;Object&gt;
        ///				&lt;DatabaseID&gt;
        ///					&lt;xsl:value-of select=&quot;$TargetDatabase&quot;&gt;&lt;/xsl:value-of&gt;
        ///				&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployMdxScript {
            get {
                return ResourceManager.GetString("DeployMdxScript", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon DeployMdxScriptIcon {
            get {
                object obj = ResourceManager.GetObject("DeployMdxScriptIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon EditAggregations {
            get {
                object obj = ResourceManager.GetObject("EditAggregations", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon EstimatedCounts {
            get {
                object obj = ResourceManager.GetObject("EstimatedCounts", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ExpressionListIcon {
            get {
                object obj = ResourceManager.GetObject("ExpressionListIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] Konesans_Dts_CommonLibrary {
            get {
                object obj = ResourceManager.GetObject("Konesans_Dts_CommonLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon RefreshExpressions {
            get {
                object obj = ResourceManager.GetObject("RefreshExpressions", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:DTS=&quot;www.microsoft.com/SqlServer/Dts&quot;&gt;
        ///	&lt;xsl:output cdata-section-elements=&quot;ProjectItem arrayElement&quot;/&gt;
        ///
        ///	&lt;xsl:template match=&quot;node()&quot;&gt;
        ///		&lt;xsl:copy&gt;
        ///			&lt;!-- leave default sort order --&gt;
        ///			&lt;xsl:apply-templates select=&quot;@*|node()[name()!=&apos;DTS:LogProvider&apos; and name()!=&apos;DTS:Executable&apos; and name()!=&apos;DTS:ConnectionManager&apos; and name()!=&apos;DTS:PrecedenceConstraint&apos; and name()!=&apos;component&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmartDiffDtsx {
            get {
                return ResourceManager.GetString("SmartDiffDtsx", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
